# SkyBlockProject Ana Konfigürasyon Dosyası
# Plugin: SkyBlockProject
# Yazar: Knemis

# Genel Plugin Ayarları
general:
  # Plugin'in mesajlarda kullanacağı genel ön ek.
  plugin-prefix: "&b[SkyBlock] &r"
  # Tarih ve sayı formatları gibi yerelleştirme ayarları için. (örn: tr-TR, en-US)
  locale: "tr-TR"
  # Yeni adaların X koordinatında ne kadar aralıkla oluşturulacağını belirler.
  island.spacing: 300
  # Bir sonraki oluşturulacak adanın X koordinatı. Plugin bu değeri otomatik günceller.
  next-island-x: 0 # Bu değeri elle değiştirmeyin.
  # Skyblock adalarının bulunacağı dünyanın adı.
  skyblock-world-name: "skyblock_world"

# Ada Ayarları
island:
  # Yeni oluşturulan adalar için varsayılan isim ön eki. Oyuncu adı buna eklenir.
  default-name-prefix: "Ada" # Örnek: "Ada-KullaniciAdi"
  # Ada oluşturmanın bir maliyeti olacaksa, buraya miktarını girin. 0 ise ücretsizdir.
  creation-cost: 1000.0
  # Tekrar ada oluşturma komutunu kullanmak için bekleme süresi (saniye cinsinden).
  creation-cooldown-seconds: 300 # 5 dakika
  # Bir adanın sahip olabileceği maksimum üye sayısı.
  max-members: 5
  # Oyuncuların bir adada ayarlayabileceği maksimum ev (home) sayısı (başlangıçta).
  max-named-homes: 3
  # Ada ismi için geçerlilik deseni (RegEx).
  name:
    pattern: "^[a-zA-Z0-9_\\- ÇçĞğİıÖöŞşÜü]{3,25}$" # Türkçe karakterler dahil
    min-length: 3
    max-length: 25
  # Ada ev isimleri için geçerlilik deseni (RegEx).
  home-name-pattern: "^[a-zA-Z0-9_]{2,16}$"
  # Ada karşılama mesajının maksimum karakter uzunluğu.
  welcome-message:
    max-length: 100
  # Ada sınırlarının (PlayerBoundaryListener tarafından) aktif olup olmayacağı.
  enforce-boundaries: true
  # WorldGuard bölge önceliği. Diğer eklentilerle çakışmaları önlemek için gerekebilir.
  region-priority: 10
  # Ada şematiği dosyasının adı (plugin'in data klasöründe bulunmalı).
  schematic-file-name: "island.schem"
  # Ada şematiğinden itibaren bölge genişletme ayarları.
  expansion:
    radius-horizontal: 50 # Yatay genişleme yarıçapı (blok).
    radius-vertical-bottom: 20 # Şematik tabanından aşağı doğru dikey genişleme.
    allow-build-below-schematic-base: false # Şematik tabanının altına inşa izni.
    build-limit-above-schematic-top: 150 # Şematik tepesinden yukarı doğru inşa limiti.
  # Ada ışınlanma noktası için şematik tabanından ofsetler.
  spawn-offset:
    x: 0.5
    y: 1.5
    z: 0.5
  # Ada silme ve sıfırlama komutları için onay bekleme süresi (saniye).
  delete-confirm-timeout-seconds: 30
  reset-confirm-timeout-seconds: 30
  # Ada geliştirmeleri
  upgrades:
    homes:
      # Ev limiti yükseltme başına maliyet.
      cost_per_upgrade: 50000.0
      # Her yükseltmede ev limitine eklenecek miktar.
      increment_amount: 1
      # Bir adanın sahip olabileceği maksimum toplam ev sayısı.
      max_possible_total_homes: 10
  # Ada Değer Sistemi Ayarları
  worth:
    # Blokların parasal değerleri. Format: MATERYAL_ADI: DEĞER
    block_values:
      DIAMOND_BLOCK: 150.0
      EMERALD_BLOCK: 120.0
      GOLD_BLOCK: 80.0
      IRON_BLOCK: 40.0
      NETHERITE_BLOCK: 500.0
      BEACON: 1000.0
      SPONGE: 25.0
      STONE: 0.1
      COBBLESTONE: 0.05
      DIRT: 0.01
      GRASS_BLOCK: 0.02
      OAK_LOG: 0.5
      # ... diğer bloklar eklenebilir ...
    # Ada seviyeleri için gereken minimum ada değeri.
    level_requirements:
      1: 0.0
      2: 10000.0
      3: 50000.0
      4: 150000.0
      5: 500000.0
      10: 2000000.0
      # ... daha fazla seviye ...
    # Seviye atlama ödülleri.
    # {player} = oyuncu adı, {island_owner_uuid} = ada sahibi UUID, {island_level} = yeni seviye
    # Sadece sayı girilirse, para ödülü olarak verilir (eco give {player} MİKTAR).
    level_up_rewards:
      2: "eco give {player} 2500"
      3: "broadcast {player} adası {island_level}. seviyeye ulaştı! Ödül: 5000 para!"
      5: 15000.0 # "eco give {player} 15000.0" olarak çalışır
      10: "crate key give {player} efsanevi_ada 1"
  # Varsayılan Ada Bayrakları (IslandFlagManager bu değerleri okuyacak şekilde güncellenmeli)
  # Bu bayraklar, ada ilk oluşturulduğunda bölgeye uygulanır.
  # Olası değerler: ALLOW, DENY, veya boş bırakılırsa (veya NONE yazılırsa) WorldGuard varsayılanı.
  default-flags:
    # Temel Koruma Bayrakları (Ziyaretçiler ve Genel Üyeler için Kısıtlayıcı)
    PASSTHROUGH: "ALLOW"  # Genel olarak adaya girişe izin verilir, ada sahibi isterse /island settings ile kapatabilir.
    BUILD: "DENY"         # WorldGuard'ın kendi varsayılanı genellikle üyelere izin verir, bu daha kısıtlayıcı.
    BLOCK_BREAK: "DENY"   # Blok kırmayı engeller
    BLOCK_PLACE: "DENY"   # Blok yerleştirmeyi engeller
    INTERACT: "DENY"      # Genel etkileşimleri kısıtlar (örn: redstone olmayan bloklar, yataklar)
    USE: "DENY"           # Kapı, düğme, manivela vb. kullanımını engeller
    CHEST_ACCESS: "DENY"  # Sandık ve diğer envanter bloklarına erişimi engeller
    DAMAGE_ANIMALS: "DENY"# Hayvanlara zarar vermeyi engeller
    PVP: "DENY"           # Oyuncular arası savaşı engeller
    TNT: "DENY"           # TNT hasarını ve patlamasını engeller (WorldGuard'ın TNT bayrağı patlamayı engeller, hasarı değil, bu genel bir kısıtlama)

    # Etkileşim ve Kullanım Kolaylığı Bayrakları
    ITEM_PICKUP: "ALLOW"  # Ziyaretçilerin yerdeki eşyaları toplamasına izin ver (isteğe bağlı)
    ITEM_DROP: "DENY"     # Ziyaretçilerin adaya eşya bırakmasını engeller (spam önleme)
    EXP_DROPS: "ALLOW"    # EXP kürelerinin düşmesine izin ver
    ENDERPEARL: "ALLOW"   # Ziyaretçilerin ender pearl kullanmasına izin ver
    MOB_SPAWNING: "ALLOW" # Doğal mob spawn olmasına izin ver (ada sahibi farmlar için isteyebilir)
    RIDE: "DENY"          # Ziyaretçilerin hayvanlara veya araçlara binmesini engeller

    # Çevresel Bayraklar
    LAVA_FLOW: "DENY"     # Lav akışını engeller
    WATER_FLOW: "DENY"    # Su akışını engeller
    FIRE_SPREAD: "DENY"   # Ateşin yayılmasını engeller

    # Özel Eklenti Bayrakları
    VISITOR_SHOP_USE: "ALLOW" # Özel dükkan kullanma bayrağı

    # Diğer Önemli Olabilecek WorldGuard Bayrakları (varsayılanları genellikle yeterlidir veya ada sahibi ayarlar)
    # GREET_MESSAGE: ""
    # FAREWELL_MESSAGE: ""
    # GRASS_GROWTH: "ALLOW" # Çimlerin büyümesi
    # MYCELIUM_SPREAD: "ALLOW" # Miselyumun yayılması
    # VINE_GROWTH: "ALLOW" # Sarmaşıkların büyümesi
    # SNOW_FALL: "ALLOW" # Kar yağışı (biyoma bağlı)
    # SNOW_MELT: "ALLOW" # Karın erimesi
    # ICE_FORM: "ALLOW" # Buz oluşumu
    # ICE_MELT: "ALLOW" # Buzun erimesi
    # LIGHTNING: "DENY" # Yıldırım düşmesi
    # PISTONS: "DENY" # Ziyaretçilerin piston kullanması (USE kapsamalı ama daha spesifik olabilir)

# Dükkan Sistemi Ayarları
shop:
  # Dükkan sahibi tarafından belirlenebilecek maksimum dükkan adı uzunluğu.
  max_display_name_length: 30
  # Dükkan tabelasındaki ilk satır (renk kodları & ile kullanılabilir).
  sign_header: "&1[Dükkan]" # Örnek: "[Shop]" veya "[Mağaza]"

# Ekonomi Ayarları
economy:
  # Vault'tan para birimi adı/sembolü alınamazsa veya özel bir sembol isteniyorsa kullanılır.
  currency-symbol: "₺"

# Komut Maliyetleri
# Komutların kullanılabilmesi için oyuncudan çekilecek miktar. 0 ise ücretsiz.
commands:
  sethome:
    cost: 50.0
  settings_name: # Ada ismi değiştirme
    cost: 1000.0 # Örnek bir değer, önceki 50000.0 çok yüksek olabilir
  biome_set: # Ada biyomu değiştirme
    cost: 10000.0
  # Örnek: /island upgrade <tür> için genel bir maliyet veya türe özel maliyetler
  # upgrade:
  #   default_cost: 25000.0
  #   homes_cost: 50000.0 # 'island.upgrades.homes.cost_per_upgrade' ile aynı, burada merkezileştirilebilir

# Görev Sistemi Ayarları
missions:
  gui:
    # Görevler ana GUI'sinde sayfa başına gösterilecek görev sayısı.
    missions-per-page: 28 # 4 satır x 7 sütun (kenarlar hariç 54 slotluk GUI için)
    # Daha fazla görev için 36 veya 45 (5 satır) düşünülebilir.
    # ShopSetupListener'daki ITEM_PLACEMENT_SLOT = 13 gibi,
    # GUI slot numaraları genellikle kod içinde sabit kalır,
    # ancak sayfa başına görev sayısı gibi daha genel ayarlar config'e alınabilir.

# Loglama Ayarları
logging:
  # WorldGuard bayrak değişikliklerinin konsolda detaylı loglanıp loglanmayacağı.
  detailed-flag-changes: false
  # LuckPerms izin değişikliklerinin konsolda detaylı loglanıp loglanmayacağı.
  detailed-luckperms-changes: false
  # Dükkan işlemleri (alış/satış/oluşturma) detaylı loglansın mı?
  detailed-shop-transactions: false