island:
  welcome-message:
    max-length: 100
    creation-cost: 0.0

commands: # Yeni bölüm
  sethome:
    cost: 50.0
  biome_set:
    cost: 10000.0
  settings_name:
    cost: 50000.0



logging:
  detailed-flag-changes: true


skyblock-world-name: "skyblock_world"

island-spawn-offset:
  x: 0.5
  y: 1.5 # Şematiğinizin zemininden ne kadar yukarıda olacağı
  z: 0.5