island:

 welcome-message:
 max-length: 100
 max-named-homes: 3
 creation-cost: 0.0
 upgrades: # YENİ BÖLÜM
   homes:
    increment_amount: 1            # Her yükseltmede ev limitine eklenecek miktar
    cost_per_upgrade: 2000.0       # Her bir yükseltmenin maliyeti
    max_possible_total_homes: 10


commands: # Yeni bölüm
  sethome:
    cost: 50.0
  biome_set:
    cost: 10000.0
  settings_name:
    cost: 50000.0



logging:
  detailed-flag-changes: true


skyblock-world-name: "skyblock_world"

island-spawn-offset:
  x: 0.5
  y: 1.5 # Şematiğinizin zemininden ne kadar yukarıda olacağı
  z: 0.5