name: SkyBlockProject
version: '${version}'
main: com.knemis.skyblock.skyblockcoreproject.SkyBlockProject
api-version: '1.21'
authors: [Knemis]
description: KnemisSkyblockProject
depend: # Eklentinizin çalışması için KESİNLİKLE GEREKLİ olan eklentiler
  - FastAsyncWorldEdit
  - WorldGuard
  - Vault

softdepend: # EKLENDİ
  - LuckPerms
  - Essentials

commands:
  island:
    description: Temel Skyblock ada komutları.
    usage: /<command> [create | ...] # Oyuncuya komutun nasıl kullanılacağını gösterir
    aliases: [i, is] # Komut için alternatif isimler (isteğe bağlı)
  missions:
    description: Access and manage your island missions.
    aliases: [mission, quests, quest, challenges]
    usage: /<command> [gui|open]
    permission: skyblock.missions.access