name: SkyBlockProject
version: '${version}'
main: com.knemis.skyblock.skyblockcoreproject.SkyBlockProject
api-version: '1.16'
authors: [Knemis]
description: KnemisSkyblockProject
depend: # Eklentinizin çalışması için KESİNLİKLE GEREKLİ olan eklentiler
  - WorldEdit
  - WorldGuard

commands:
  island:
    description: Temel Skyblock ada komutları.
    usage: /<command> [create | ...] # Oyuncuya komutun nasıl kullanılacağını gösterir
    aliases: [i, is] # Komut için alternatif isimler (isteğe bağlı)